# Generated by Django 4.2.9 on 2026-02-23 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('watering_frequency_days', models.IntegerField(default=7)),
                ('native', models.BooleanField(default=True)),
                ('icon', models.CharField(default='🌳', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Species',
                'ordering': ['common_name'],
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_description', models.CharField(blank=True, help_text='e.g. Near Gate 3, South side', max_length=255)),
                ('current_health', models.CharField(choices=[('healthy', 'Healthy'), ('at_risk', 'At Risk'), ('dead', 'Dead')], default='healthy', max_length=20)),
                ('planted_date', models.DateField()),
                ('height_cm', models.IntegerField(blank=True, null=True)),
                ('tag_number', models.CharField(blank=True, help_text='Physical tag on the tree', max_length=50, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trees/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planted_trees', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trees', to='trees.species')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='zones.zone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_health', models.CharField(blank=True, max_length=20)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('at_risk', 'At Risk'), ('dead', 'Dead')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='health_logs/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='trees.tree')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
